//! The server: tool definitions (their descriptions are what a model reads) and the protocol handler.

use super::ServerOptions;
use super::params::FindParams;
use super::params::FormatParams;
use super::params::InsertParams;
use super::params::RemoveParams;
use super::params::RenameParams;
use super::params::ReplaceParams;
use super::params::Selection;
use super::params::ViewParams;
use super::render;
use super::tools;
use super::tools::Cancelled;
use super::tools::Output;
use super::worker;
use crate::workspace::LoadOptions;
use rmcp::ErrorData;
use rmcp::RoleServer;
use rmcp::ServerHandler;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::tool::ToolCallContext;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::CallToolRequestParams;
use rmcp::model::CallToolResponse;
use rmcp::model::CallToolResult;
use rmcp::model::ContentBlock;
use rmcp::model::Implementation;
use rmcp::model::ServerCapabilities;
use rmcp::model::ServerConfig;
use rmcp::service::RequestContext;
use rmcp::tool;
use rmcp::tool_handler;
use rmcp::tool_router;
use std::convert::identity;
use std::sync::Arc;
use tokio::sync::Mutex;

/// Guidance for the client (and its model), sent when connecting.
const INSTRUCTIONS: &str = "\
rscode views, searches, and edits the Rust crates of a cargo workspace by item path. Nothing is compiled or expanded: \
items generated by macros are invisible.

Item paths are written like Rust paths: `crate::module::Item` (from the root of every selected crate), \
`::crate_name::Item`, or a bare `module::Item`, which is tried from every crate root (and as `::module::Item` when \
`module` is a crate name). Associated items: `Type::method`, `Trait::method`, `<Type as Trait>::method`; impl blocks: \
`impl Trait for Type`, `impl Type`; enum variants: `Enum::Variant`; `crate` is the crate root module. Generic \
arguments of the type and trait pick impl blocks: `impl From<u8> for Wrapper`, `<Wrapper<u16>>::get`. A path names \
every cfg variant of an item: items under disabled cfgs are included, and marked inactive.

find_items takes glob patterns: `*` matches within one path segment (`parse_*`, `*Error`), `**` any number of \
segments (`crate::config::**`, `**::tests::*`). A pattern that does not start with `crate::` or `::` matches anywhere: \
`Config::load` finds `my_crate::config::Config::load`.

Edits (rename_item, remove_items, replace_item, insert_items, format_items) are all-or-nothing: every changed file \
must still parse, or nothing is written. Set `dry_run` (`check` for format_items) to get a unified diff without \
writing anything. Comments and formatting outside of the edited items are preserved.

The workspace is loaded from disk again for every call, so changes made by other tools are always seen. Lines and \
columns are 1-based. Typically: workspace_info to see the crates, find_items to locate items, view_items to read \
them, then edit.";

/// Appended to [`INSTRUCTIONS`] for read-only servers.
const READ_ONLY_INSTRUCTIONS: &str = "\n\nThis server is read-only: the editing tools are disabled.";

/// The rscode MCP server.
pub(crate) struct Server {
	options: ServerOptions,

	/// Every tool; the editing tools are disabled when the server is read-only.
	tool_router: ToolRouter<Self>,

	/// Held by an editing call for its whole run, on its worker thread: edits never interleave, and shutdown can wait
	/// for an edit that is still writing even when its request is gone.
	edits: Arc<Mutex<()>>,
}

impl Server {
	pub(crate) fn new(options: ServerOptions) -> Self {
		let mut tool_router = Self::query_tools() + Self::edit_tools();

		if options.read_only {
			for name in Self::edit_tools().map.into_keys() {
				tool_router.disable_route(name);
			}
		}

		Self {
			options,
			tool_router,
			edits: Arc::default(),
		}
	}

	/// The lock editing calls hold while they run.
	pub(crate) fn edit_lock(&self) -> Arc<Mutex<()>> {
		self.edits.clone()
	}

	/// The tools the server offers.
	#[cfg(test)]
	pub(crate) fn tools(&self) -> Vec<rmcp::model::Tool> {
		self.tool_router.list_all()
	}

	/// The server's load options with a call's selection.
	fn load_options(&self, selection: &Selection) -> LoadOptions {
		selection.apply(&self.options.load)
	}

	/// Like [`Server::load_options`], also loading every other target of every workspace member, so that references
	/// everywhere are found.
	fn load_everything(&self, selection: &Selection) -> LoadOptions {
		LoadOptions {
			load_all_members: true,
			..self.load_options(selection)
		}
	}

	/// Runs a read-only tool's job.
	async fn query(&self, name: &'static str, job: impl FnOnce() -> Output + Send + 'static) -> CallToolResult {
		respond(name, worker::run(name, job).await.and_then(identity))
	}

	/// Runs an editing tool's job, one at a time. The job is told whether the request was cancelled, to write
	/// nothing if so.
	async fn edit(
		&self,
		name: &'static str,
		context: RequestContext<RoleServer>,
		job: impl FnOnce(Cancelled<'_>) -> Output + Send + 'static,
	) -> CallToolResult {
		if self.options.read_only {
			return read_only(name);
		}

		let guard = self.edits.clone().lock_owned().await;
		let token = context.ct;
		let result = worker::run(name, move || {
			let _guard = guard;

			job(&|| token.is_cancelled())
		})
		.await;

		respond(name, result.and_then(identity))
	}
}

#[tool_router(router = query_tools)]
impl Server {
	/// Describe the workspace: its packages (version, manifest, features with the enabled ones marked `*`), its crates
	/// (name, kind, root file, edition, whether selected), and the problems found while loading (files that do not
	/// parse, missing module files). Call this first to learn the crate names.
	#[tool(annotations(
		title = "Workspace info",
		read_only_hint = true,
		idempotent_hint = true,
		open_world_hint = false
	))]
	async fn workspace_info(&self, Parameters(selection): Parameters<Selection>) -> CallToolResult {
		let load = self.load_options(&selection);

		self.query("workspace_info", move || tools::workspace_info(&load)).await
	}

	/// Find items whose paths match a glob pattern (`*` within a path segment, `**` across segments). Prints one
	/// line per item: `path  kind  file:line:col-endline:endcol`, followed by `cfg: …` for items behind a cfg,
	/// `inactive` when that cfg is disabled (`cfg-unknown` when undecidable), `-> target` for imports, and the
	/// usable paths when `from` is given.
	#[tool(annotations(title = "Find items", read_only_hint = true, idempotent_hint = true, open_world_hint = false))]
	async fn find_items(&self, Parameters(params): Parameters<FindParams>) -> CallToolResult {
		let load = self.load_options(&params.selection);

		self.query("find_items", move || tools::find(&load, &params)).await
	}

	/// Show the source of items by path: in full, or outlined with bodies elided (the default for modules and
	/// crates). Every item starts with a header line `// path (kind) file:line-endline`, followed by its lines,
	/// numbered as in the file.
	#[tool(annotations(title = "View items", read_only_hint = true, idempotent_hint = true, open_world_hint = false))]
	async fn view_items(&self, Parameters(params): Parameters<ViewParams>) -> CallToolResult {
		let load = self.load_options(&params.selection);

		self.query("view_items", move || tools::view(&load, &params)).await
	}
}

#[tool_router(router = edit_tools)]
impl Server {
	/// Rename an item (every cfg variant) and update the references to it in every crate of the workspace: paths in
	/// code, imports, re-exports, and for out-of-line modules the module's file. Refuses a new name that collides with
	/// an existing one unless `force`.
	///
	/// Method calls, names inside of macros, and doc links cannot be resolved with certainty: they are listed as
	/// possible references, and only renamed with `method_calls`, `macro_tokens`, and `doc_links`. Set `dry_run` to
	/// review the diff first.
	#[tool(annotations(
		title = "Rename an item",
		read_only_hint = false,
		destructive_hint = false,
		open_world_hint = false
	))]
	async fn rename_item(
		&self,
		Parameters(params): Parameters<RenameParams>,
		context: RequestContext<RoleServer>,
	) -> CallToolResult {
		let load = self.load_everything(&params.selection);

		self.edit("rename_item", context, move |cancelled| tools::rename(&load, &params, cancelled)).await
	}

	/// Remove items (every cfg variant) with their doc comments, attributes, and attached comments. Removing an
	/// out-of-line module also deletes its files unless `keep_files`; `prune_imports` also removes imports of the
	/// removed items. Reports references that are left dangling. Set `dry_run` to review the diff first.
	#[tool(annotations(
		title = "Remove items",
		read_only_hint = false,
		destructive_hint = true,
		open_world_hint = false
	))]
	async fn remove_items(
		&self,
		Parameters(params): Parameters<RemoveParams>,
		context: RequestContext<RoleServer>,
	) -> CallToolResult {
		let load = self.load_everything(&params.selection);

		self.edit("remove_items", context, move |cancelled| tools::remove(&load, &params, cancelled)).await
	}

	/// Replace the whole source of an item, including its doc comments and attributes, with `source`: one item of the
	/// same kind (unless `allow_kind_change`), re-indented to fit. Get the current source first with `view_items`
	/// (`mode` `full`, `line_numbers` false). Set `dry_run` to review the diff first.
	#[tool(annotations(
		title = "Replace an item",
		read_only_hint = false,
		destructive_hint = true,
		open_world_hint = false
	))]
	async fn replace_item(
		&self,
		Parameters(params): Parameters<ReplaceParams>,
		context: RequestContext<RoleServer>,
	) -> CallToolResult {
		let load = self.load_options(&params.selection);

		self.edit("replace_item", context, move |cancelled| tools::replace(&load, &params, cancelled)).await
	}

	/// Insert new items into a module (`crate` for the crate root; set `lib` or `bin` to pick the library or a binary
	/// of a package that has both), an impl block (`impl Trait for Type`, `impl Type`), or a trait: at its end, at its
	/// start, or before or after a sibling item (`anchor`). The items are indented to fit and separated by blank lines.
	/// Refuses names that are already taken unless `force`. Set `dry_run` to review the diff first.
	#[tool(annotations(
		title = "Insert items",
		read_only_hint = false,
		destructive_hint = false,
		open_world_hint = false
	))]
	async fn insert_items(
		&self,
		Parameters(params): Parameters<InsertParams>,
		context: RequestContext<RoleServer>,
	) -> CallToolResult {
		let load = self.load_options(&params.selection);

		self.edit("insert_items", context, move |cancelled| tools::insert(&load, &params, cancelled)).await
	}

	/// Sort items (Cryotheum ordering) and format them with rustfmt or prettyplease. A module target formats its
	/// whole file, and its child modules' files unless `skip_children`; other targets are formatted in place without
	/// touching the rest of the file. Set `check` to get the diff without writing.
	#[tool(annotations(
		title = "Format items",
		read_only_hint = false,
		destructive_hint = false,
		idempotent_hint = true,
		open_world_hint = false
	))]
	async fn format_items(
		&self,
		Parameters(params): Parameters<FormatParams>,
		context: RequestContext<RoleServer>,
	) -> CallToolResult {
		let load = self.load_options(&params.selection);

		self.edit("format_items", context, move |cancelled| tools::format(&load, &params, cancelled)).await
	}
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for Server {
	fn get_info(&self) -> ServerConfig {
		let mut instructions = INSTRUCTIONS.to_owned();

		if self.options.read_only {
			instructions.push_str(READ_ONLY_INSTRUCTIONS);
		}

		let implementation = Implementation::new("rscode", env!("CARGO_PKG_VERSION"))
			.with_title("rscode")
			.with_description("View, search, and edit Rust source files by item path");

		ServerConfig::new(ServerCapabilities::builder().enable_tools().build())
			.with_server_info(implementation)
			.with_instructions(instructions)
	}

	async fn call_tool(
		&self,
		request: CallToolRequestParams,
		context: RequestContext<RoleServer>,
	) -> Result<CallToolResponse, ErrorData> {
		// the editing tools of a read-only server are hidden: tell why rather than "tool not found"
		if self.tool_router.is_disabled(&request.name) {
			return Ok(read_only(&request.name).into());
		}

		self.tool_router.call(ToolCallContext::new(self, request, context)).await
	}
}

/// A tool's result for the client: text, or an error the model can react to. Overlong text is truncated.
fn respond(tool: &str, result: Result<String, String>) -> CallToolResult {
	let truncate = |text| render::truncate(text, render::MAX_OUTPUT_CHARS, render::truncation_hint(tool));

	match result {
		Ok(text) => CallToolResult::success(vec![ContentBlock::text(truncate(text))]),
		Err(message) => CallToolResult::error(vec![ContentBlock::text(truncate(message))]),
	}
}

fn read_only(tool: &str) -> CallToolResult {
	CallToolResult::error(vec![ContentBlock::text(format!(
		"`{tool}` modifies files, but this rscode server is read-only (it was started with `--read-only`)"
	))])
}
